name: Build and Deploy Spring Boot to AWS EC2
on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: cicdproject
  BUCKET_NAME: cicd-codedeploy-andol06  # 사용자님이 만든 S3 버킷 이름으로 수정!
  CODE_DEPLOY_APP_NAME: cicdapp
  DEPLOYMENT_GROUP_NAME: cicdapp_deploy
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. 자바 설치
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 2. 권한 부여 (이게 있어야 빌드가 됩니다)
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 3. 진짜 빌드 (이게 .jar 파일을 만듭니다)
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip . # 현재 폴더 전체를 압축
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp --region ${{ env.AWS_REGION }} ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name $CODE_DEPLOY_APP_NAME \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name $DEPLOYMENT_GROUP_NAME \
            --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip